### PR TITLE
UX wireframe with HTML

### PR DESCRIPTION
**Pull request by wild-boomerang**
https://www.figma.com/file/v2kr961ayJvPo7Ry0SiaTe/Vladello?node-id=0%3A1

### CODE REVIEW

**Review by gmltA — CHANGES_REQUESTED** [review]
- Clickable elements should be represented by interactive HTML tags (e.g. `button`).
- Text that describes the `input` should be wrapper in a `label`.

**Comment by wild-boomerang** [comment]
I think I fixed it.

**Review by gmltA — APPROVED** [review]
Good. It's <kbd>8</kbd>.

**Comment by wild-boomerang** [comment]
Ok, thanks.

**Review by gmltA — APPROVED** [review]

**Pull request merged**
