### PR TITLE
UI design

### PR DESCRIPTION
**Pull request by wild-boomerang**

### CODE REVIEW

**Comment by gmltA** [comment]
Website link?

**Comment by wild-boomerang** [comment]
Boards and cards: https://wild-boomerang.github.io/trello-alike-app/html/boards.html
Login and registration: https://wild-boomerang.github.io/trello-alike-app/html/login.html

**Review by gmltA — COMMENTED** [review]
That's a <kbd>8</kbd>. Tell me if you are ok with that.

**Comment by wild-boomerang** [comment]
That's enough, thanks.

**Review by gmltA — APPROVED** [review]

**Pull request merged**
